# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7af85950ffcf1b70a32bc7ad1c03bb6ffd19c1760149b7d90e26548a87bc7fa2af7240245ba77cac977bc3190857789e03db37f80f4a9f45cda79ba6cefd7e0c

test:
  secret_key_base: a52335434601d115eab5e858fbd930dc2a345f22fabc8b0c42ef4eb490d10cc9ec61203065e2a5334e5ecbf74c7a8f709a6741809be16f85c215cfb0445680ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
